### ISSUE TITLE
【履歴保存】家事のリストが表示された画面をユーザーが見れる

### ISSUE THREAD

**Issue by syun123456789** [kuroneko-hornet/household_chore_record_app#4]
【完了条件】
- [x] 家事のリストが定義されていること
- [x] 家事のリストがTOP画面に表示されていること

**Comment by syun123456789** [comment]
【家事のリスト】
- 掃除
  1. 床（廊下、ダイニング）
  2. お風呂 (排水口, 床）
  3. お風呂の浴槽
  4. 洗面所（鏡､洗面台）
  5. キッチン（壁、コンロ、流し、作業台）
  6. トイレ（床、便器）
  7. 玄関
  8. 掃除機の掃除
  9. テーブル
- 料理 （昼・夜　※2人分以上作成時のみ）
- 洗濯
  1. 乾燥物洗濯開始
  2. 乾燥しないもの洗濯開始
  3. 洗濯終了後処理（乾燥物：かごに入れる 乾燥しないもの：干す）
- ごみまとめ（ごみ袋にまとめて新しいごみ袋をセットするまで）
- ごみ出し
- 買い出し（3人用の食材・日用品、オンライン不可）
- 荷物受け取り
- 食器
  1. 洗う
  2. 片付け
- 米
  1. 炊飯
  2. 冷凍
- 補充
  1. 洗濯用洗剤
  2. 食器用洗剤
  3. ハンドソープ
  4. トイレットペーパー
- 精算処理
- 軽微な家事（上記に該当しない家事）
- 製氷

**Comment by kuroneko-hornet** [comment]
* ゴミ出し分ける必要ある？いずれかやったら1回でいいのでは？
* ゴミまとめも同上
  * でも不燃って何やるのか明確じゃないな。。。
* 洗濯乾燥は乾燥かごに入れるの扱いは？
* 買い出しはたとえば俺は車で重たいものまとめて買ったりしたいな〜コメとかね。ちょっと区分はどうしたらいいか考えないとな。一旦まとめて1回でもいい。
* 下記が入ってないね。
  * 食器洗い
  * 炊飯
  * 食事前にテーブル片付ける（そもそも入れるのか？）
  * 洗剤、石鹸などの補充
  * 掃除機の掃除
  * 精算の集計
  * 補足：「軽微な家事」ってやつ入れてもいいかもね。その他的な扱いで。

**Comment by syun123456789** [comment]
- ゴミ出し分ける必要ある？いずれかやったら1回でいいのでは？
→出し忘れ防止に繋がるかと思ったけど曜日でわかるからいいか

- ゴミまとめも同上
→OK

- でも不燃って何やるのか明確じゃないな。。。
→対象は少ないけど、割れ物とか電池はひと手間あるから分けたほうがいいか？

- 洗濯乾燥は乾燥かごに入れるの扱いは？
→起動後に同じ人がやる可能性は低いから、かご入れは分けようか
　その理屈でいうと干すのも同じことがいえるから、洗濯機起動と後処理で分けようと思う


- 買い出しはたとえば俺は車で重たいものまとめて買ったりしたいな〜コメとかね。ちょっと区分はどうしたらいいか考えないとな。一旦まとめて1回でもいい。
→OK

- 下記が入ってないね。
  - 食器洗い
  - 炊飯
  - 食事前にテーブル片付ける（そもそも入れるのか？）
  - 洗剤、石鹸などの補充
  - 掃除機の掃除
  - 補足：「軽微な家事」ってやつ入れてもいいかもね。その他的な扱いで。
→OK、反映する
